# Generated by Django 4.1.2 on 2022-10-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
