# Generated by Django 4.1.2 on 2022-10-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='notes',
            field=models.TextField(default='car_details'),
            preserve_default=False,
        ),
    ]
