# Generated by Django 4.1.2 on 2022-10-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0005_rename_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=250),
        ),
    ]
